#!/usr/bin/env python3
"""build_manifest.py — (re)generate work/lectures.tsv from the videos in videos/.

The manifest lives in work/ with the rest of the course-specific material (work/ is
the private half of the project; everything outside it is the tool).

Lecture number = the LAST run of digits in the filename stem
(CSDA26_1 -> L01, CSDA2023-5 -> L05), so recordings from mixed years form one
continuous series. Existing param/note values are preserved across regeneration,
so you can safely re-run this whenever you drop in a new video.

Usage:
  python scripts/build_manifest.py                 # videos/ -> work/lectures.tsv
  python scripts/build_manifest.py --videos videos --out work/lectures.tsv
"""
from __future__ import annotations
import argparse, re, sys
from pathlib import Path

SOURCE_EXTS = {".mp4", ".mov", ".m4v", ".mkv", ".pdf"}   # .pdf = a lecture delivered as a document


def lecture_num(stem: str):
    runs = re.findall(r"\d+", stem)
    return int(runs[-1]) if runs else None


def read_existing(tsv: Path) -> dict:
    keep = {}
    if not tsv.exists():
        return keep
    for line in tsv.read_text().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if parts and parts[0].strip():
            keep[parts[0].strip()] = {
                "threshold": parts[2].strip() if len(parts) > 2 else "-",
                "note": parts[3].strip() if len(parts) > 3 else "",
            }
    return keep


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--videos", default="videos")
    ap.add_argument("--out", default="work/lectures.tsv")
    args = ap.parse_args()

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    vdir = Path(args.videos)
    vids = sorted(p for p in vdir.iterdir() if p.suffix.lower() in SOURCE_EXTS) \
        if vdir.is_dir() else []
    old = read_existing(Path(args.out))

    rows, seen, warn = [], {}, []
    for p in vids:
        n = lecture_num(p.stem)
        if n is None:
            warn.append(f"no trailing number, skipped: {p.name}")
            continue
        lid = f"L{n:02d}"
        if lid in seen:
            warn.append(f"DUPLICATE {lid}: {seen[lid]} vs {p.name} — resolve manually")
        seen[lid] = p.name
        prev = old.get(lid, {})
        rows.append((n, lid, f"{args.videos}/{p.name}",
                     prev.get("threshold") or "-",
                     prev.get("note") or p.stem))
    rows.sort()

    header = [
        "# Lecture manifest — drives scripts/prepare_all.sh",
        "# Auto-generated by scripts/build_manifest.py (re-run after adding videos).",
        "# Lecture number = LAST digit-run in the filename (CSDA2023-5 -> L05).",
        "# TAB-separated. Columns: lecture_id  source_video  param  note",
        "# param: extra extract_pages_scroll.py flags for THIS lecture, '-' for the",
        "#        global defaults (the normal case). See README -> Tuning.",
        "#",
        "# lecture_id\tsource_video\tparam\tnote",
    ]
    body = ["\t".join([lid, src, th, note]) for _, lid, src, th, note in rows]
    Path(args.out).write_text("\n".join(header + body) + "\n")
    print(f"[✓] wrote {args.out} with {len(rows)} lectures")
    for w in warn:
        print(f"[!] {w}", file=sys.stderr)


if __name__ == "__main__":
    main()
